export const mockClients = [
  {
    id: '1',
    name: 'Industrial Solutions SA',
    type: 'Empresa Privada',
    email: 'contact@industrial.com',
    phone: '+34 912 345 678',
    status: 'Activo',
    createdAt: '2024-01-15',
    totalOrders: 24,
    totalSpent: 45600,
    locations: [
      { id: '1-1', name: 'Sede Principal', address: 'Madrid, España', active: true },
      { id: '1-2', name: 'Almacén', address: 'Barcelona, España', active: true },
    ],
  },
  {
    id: '2',
    name: 'Municipalidad de Madrid',
    type: 'Entidad Gubernamental',
    email: 'servicios@madrid.es',
    phone: '+34 913 456 789',
    status: 'Activo',
    createdAt: '2024-02-10',
    totalOrders: 18,
    totalSpent: 32400,
    locations: [
      { id: '2-1', name: 'Ayuntamiento Central', address: 'Madrid, España', active: true },
    ],
  },
  {
    id: '3',
    name: 'García & Asociados',
    type: 'Empresa Privada',
    email: 'info@garcia.com',
    phone: '+34 934 567 890',
    status: 'Activo',
    createdAt: '2024-03-05',
    totalOrders: 12,
    totalSpent: 18900,
    locations: [
      { id: '3-1', name: 'Oficina', address: 'Barcelona, España', active: true },
    ],
  },
  {
    id: '4',
    name: 'Juan López Rodríguez',
    type: 'Cliente Particular',
    email: 'juan@email.com',
    phone: '+34 645 123 456',
    status: 'Activo',
    createdAt: '2024-04-20',
    totalOrders: 3,
    totalSpent: 2400,
    locations: [
      { id: '4-1', name: 'Residencia', address: 'Valencia, España', active: true },
    ],
  },
  {
    id: '5',
    name: 'Logística Global Iberia',
    type: 'Empresa Privada',
    email: 'ops@logistica.es',
    phone: '+34 956 789 012',
    status: 'Activo',
    createdAt: '2024-01-08',
    totalOrders: 36,
    totalSpent: 67200,
    locations: [
      { id: '5-1', name: 'Centro de Distribución', address: 'Sevilla, España', active: true },
      { id: '5-2', name: 'Almacén Norte', address: 'Bilbao, España', active: true },
    ],
  },
]

export const mockTechnicians = [
  {
    id: '1',
    name: 'Carlos Mendoza',
    email: 'carlos@taka.com',
    phone: '+34 612 345 678',
    specialties: ['Fumigación', 'Control de Plagas', 'Limpieza'],
    status: 'Disponible',
    location: 'Madrid',
    assignedOrders: 5,
    completedOrders: 127,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'María García',
    email: 'maria@taka.com',
    phone: '+34 623 456 789',
    specialties: ['Limpieza', 'Desinfección', 'Mantenimiento'],
    status: 'En Servicio',
    location: 'Barcelona',
    assignedOrders: 3,
    completedOrders: 95,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Roberto Díaz',
    email: 'roberto@taka.com',
    phone: '+34 634 567 890',
    specialties: ['Impermeabilización', 'Reparación', 'Tanques'],
    status: 'Disponible',
    location: 'Valencia',
    assignedOrders: 2,
    completedOrders: 82,
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Ana Martínez',
    email: 'ana@taka.com',
    phone: '+34 645 678 901',
    specialties: ['Fumigación', 'Trampas', 'Inspecciones'],
    status: 'Disponible',
    location: 'Sevilla',
    assignedOrders: 4,
    completedOrders: 112,
    rating: 4.8,
  },
]

export const mockOrders = [
  {
    id: 'ORD-2024-001',
    clientId: '1',
    clientName: 'Industrial Solutions SA',
    type: 'Fumigación',
    status: 'En Ejecución',
    priority: 'Alta',
    technicianId: '1',
    technicianName: 'Carlos Mendoza',
    date: '2024-05-25',
    time: '10:00',
    location: 'Madrid, España',
    description: 'Fumigación integral de almacén',
    supplies: ['Insecticida', 'Fungicida', 'Material de protección'],
    createdAt: '2024-05-20',
    progress: 65,
  },
  {
    id: 'ORD-2024-002',
    clientId: '2',
    clientName: 'Municipalidad de Madrid',
    type: 'Limpieza',
    status: 'Programada',
    priority: 'Media',
    technicianId: '2',
    technicianName: 'María García',
    date: '2024-05-26',
    time: '14:00',
    location: 'Madrid, España',
    description: 'Limpieza y desinfección de oficinas',
    supplies: ['Desinfectante', 'Escobas', 'Trapeadores'],
    createdAt: '2024-05-22',
    progress: 0,
  },
  {
    id: 'ORD-2024-003',
    clientId: '1',
    clientName: 'Industrial Solutions SA',
    type: 'Control de Plagas',
    status: 'Finalizada',
    priority: 'Media',
    technicianId: '1',
    technicianName: 'Carlos Mendoza',
    date: '2024-05-24',
    time: '09:00',
    location: 'Barcelona, España',
    description: 'Revisión de trampas y control mensual',
    supplies: ['Cebos', 'Trampas', 'Sellador'],
    createdAt: '2024-05-19',
    progress: 100,
  },
  {
    id: 'ORD-2024-004',
    clientId: '5',
    clientName: 'Logística Global Iberia',
    type: 'Mantenimiento',
    status: 'Pendiente',
    priority: 'Alta',
    technicianId: null,
    technicianName: 'Sin asignar',
    date: '2024-05-27',
    time: '08:00',
    location: 'Sevilla, España',
    description: 'Mantenimiento preventivo de instalaciones',
    supplies: ['Lubricante', 'Herramientas', 'Piezas'],
    createdAt: '2024-05-23',
    progress: 0,
  },
  {
    id: 'ORD-2024-005',
    clientId: '3',
    clientName: 'García & Asociados',
    type: 'Desinfección',
    status: 'En Ejecución',
    priority: 'Media',
    technicianId: '2',
    technicianName: 'María García',
    date: '2024-05-25',
    time: '11:00',
    location: 'Barcelona, España',
    description: 'Desinfección de oficina y áreas comunes',
    supplies: ['Desinfectante Profesional', 'Equipos de protección'],
    createdAt: '2024-05-21',
    progress: 45,
  },
]

export const mockQuotes = [
  {
    id: 'COT-2024-001',
    clientId: '1',
    clientName: 'Industrial Solutions SA',
    status: 'Enviada',
    serviceType: 'Fumigación Integral',
    amount: 2400,
    validUntil: '2024-06-01',
    createdAt: '2024-05-20',
    expiringIn: 7,
  },
  {
    id: 'COT-2024-002',
    clientId: '5',
    clientName: 'Logística Global Iberia',
    status: 'Aprobada',
    serviceType: 'Mantenimiento Mensual',
    amount: 1800,
    validUntil: '2024-06-05',
    createdAt: '2024-05-18',
    expiringIn: 11,
  },
  {
    id: 'COT-2024-003',
    clientId: '2',
    clientName: 'Municipalidad de Madrid',
    status: 'Borrador',
    serviceType: 'Limpieza Profunda',
    amount: 3500,
    validUntil: '2024-06-10',
    createdAt: '2024-05-24',
    expiringIn: 16,
  },
  {
    id: 'COT-2024-004',
    clientId: '3',
    clientName: 'García & Asociados',
    status: 'Vencida',
    serviceType: 'Control de Plagas',
    amount: 900,
    validUntil: '2024-05-10',
    createdAt: '2024-04-25',
    expiringIn: -15,
  },
]

export const mockInvoices = [
  {
    id: 'FAC-2024-001',
    orderId: 'ORD-2024-003',
    clientId: '1',
    clientName: 'Industrial Solutions SA',
    amount: 1200,
    status: 'Pagada',
    daysOverdue: 0,
    issuedAt: '2024-05-10',
    dueAt: '2024-05-30',
  },
  {
    id: 'FAC-2024-002',
    orderId: 'ORD-2024-001',
    clientId: '1',
    clientName: 'Industrial Solutions SA',
    amount: 2400,
    status: 'Pendiente',
    daysOverdue: 0,
    issuedAt: '2024-05-20',
    dueAt: '2024-06-20',
  },
  {
    id: 'FAC-2024-003',
    orderId: 'ORD-2024-005',
    clientId: '3',
    clientName: 'García & Asociados',
    amount: 850,
    status: 'Vencida',
    daysOverdue: 8,
    issuedAt: '2024-05-01',
    dueAt: '2024-05-31',
  },
  {
    id: 'FAC-2024-004',
    orderId: 'ORD-2024-002',
    clientId: '2',
    clientName: 'Municipalidad de Madrid',
    amount: 1500,
    status: 'Parcial',
    daysOverdue: 3,
    issuedAt: '2024-05-15',
    dueAt: '2024-06-15',
  },
]

export const mockSupplies = [
  {
    id: '1',
    name: 'Insecticida Profesional',
    category: 'Químicos',
    stock: 45,
    minStock: 10,
    cost: 25.50,
    unit: 'Litro',
  },
  {
    id: '2',
    name: 'Fungicida',
    category: 'Químicos',
    stock: 12,
    minStock: 10,
    cost: 35.00,
    unit: 'Litro',
  },
  {
    id: '3',
    name: 'Trampas Pegajosas',
    category: 'Trampas',
    stock: 150,
    minStock: 50,
    cost: 2.30,
    unit: 'Unidad',
  },
  {
    id: '4',
    name: 'Cebos Rodenticidas',
    category: 'Cebos',
    stock: 8,
    minStock: 20,
    cost: 18.75,
    unit: 'Caja',
  },
  {
    id: '5',
    name: 'Desinfectante Profesional',
    category: 'Químicos',
    stock: 65,
    minStock: 15,
    cost: 12.00,
    unit: 'Litro',
  },
]

export const mockAlerts = [
  {
    id: '1',
    type: 'Orden Sin Técnico',
    priority: 'Alta',
    message: 'Orden ORD-2024-004 sin técnico asignado',
    relatedId: 'ORD-2024-004',
    createdAt: '2024-05-25',
    read: false,
  },
  {
    id: '2',
    type: 'Stock Bajo',
    priority: 'Media',
    message: 'Stock bajo de Cebos Rodenticidas (8 unidades)',
    relatedId: '4',
    createdAt: '2024-05-25',
    read: false,
  },
  {
    id: '3',
    type: 'Cotización Vencida',
    priority: 'Media',
    message: 'Cotización COT-2024-004 vencida',
    relatedId: 'COT-2024-004',
    createdAt: '2024-05-24',
    read: true,
  },
  {
    id: '4',
    type: 'Factura Vencida',
    priority: 'Alta',
    message: 'Factura FAC-2024-003 vencida hace 8 días',
    relatedId: 'FAC-2024-003',
    createdAt: '2024-05-23',
    read: false,
  },
]

export const mockUsers = [
  {
    id: '1',
    name: 'Fernando Rodríguez',
    email: 'fernando@taka.com',
    role: 'Administrador',
    avatar: '👨‍💼',
    status: 'Activo',
  },
  {
    id: '2',
    name: 'José García',
    email: 'jose@taka.com',
    role: 'Coordinador Operativo',
    avatar: '👨‍🔧',
    status: 'Activo',
  },
  {
    id: '3',
    name: 'María López',
    email: 'maria.lopez@taka.com',
    role: 'Comercial',
    avatar: '👩‍💼',
    status: 'Activo',
  },
  {
    id: '4',
    name: 'Roberto Sánchez',
    email: 'roberto@taka.com',
    role: 'Finanzas',
    avatar: '👨‍💻',
    status: 'Activo',
  },
]
